management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 18086
spring:
    application:
        name: service-provider
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
            password: nacos
            username: nacos
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: 'jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf-8&usessl=false'
#        username: root
#        password: root
security:
    oauth2:
        client:
            clientID: my-trusted-client
            clientSecret: secret
        resource:
            tokenInfoUri: http://localhost:6008/oauth/check_token
