server:
    port: 18083
security:
    oauth2:
        client:
#            access-token-uri: http://localhost:6008/oauth/token
            client-id: my-trusted-client
            client-secret: secret
#            scope: read write trust
        resource:
            tokenInfoUri: http://localhost:6008/oauth/check_token
spring:
    application:
        name: service-consumer
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
            password: nacos
            username: nacos
        sentinel:
            datasource:
                ds1:
                    file:
                        data-type: json
                        file: 'classpath: flowrule.json'
                        rule-type: flow
                ds2:
                    file:
                        data-type: json
                        file: 'classpath: degraderule.json'
                        rule-type: degrade
            eager: true
            transport:
                dashboard: localhost:8080
feign:
    sentinel:
        enabled: true
management:
    endpoints:
        web:
            exposure:
                include: '*'